.gitignore
README.md
sdk-projects/README.md
sdk-projects/pack.sh
sdk-projects/tng-smpilot-ns1-emulator/nsd/nsd_smpilot_ns1_emulator.yml
sdk-projects/tng-smpilot-ns1-emulator/project.yml
sdk-projects/tng-smpilot-ns1-emulator/vnfd/vnfd_cc_emulator.yml
sdk-projects/tng-smpilot-ns1-emulator/vnfd/vnfd_eae_emulator.yml

Still no CNFs, nor multi CDU VNFDs. WIP.

Added initial version of NS1 5GTANGO SDK project. #46

---

sdk-projects/pack.sh
sdk-projects/tng-smpilot-ns1-emulator/vnfd/vnfd_cc_emulator.yml
sdk-projects/tng-smpilot-ns1-emulator/vnfd/vnfd_eae_emulator.yml

First work towards using real CNFs for the pilot. #46

---

sdk-projects/pack.sh

Fix: Removed workaround from pack.sh

---

sdk-projects/tng-smpilot-ns1-emulator/vnfd/vnfd_cc_emulator.yml
sdk-projects/tng-smpilot-ns2-emulator/vnfd/vnfd_mdc_emulator.yml
sdk-projects/tng-smpilot-ns2-emulator/vnfd/vnfd_rtr_emulator.yml
vnfs/build_emulator_vnfs.sh
vnfs/cc-cloudconnector-emulator/containers/cdu_broker/Dockerfile
vnfs/cc-cloudconnector-emulator/containers/cdu_broker/start.sh
vnfs/mdc-machinedatacollector-emulator/containers/Dockerfile
vnfs/mdc-machinedatacollector-emulator/containers/mqtt_generator.sh
vnfs/mdc-machinedatacollector-emulator/containers/start.sh

First working version that sends some random MQTT data from MDC to CC

---

vnfs/dt-digitaltwin-emulator/containers/IMMS_APP/IMMS_APP.py
vnfs/dt-digitaltwin-emulator/containers/start.sh

#55 is almost done now. Looks like things are working for Dublin ... wohooooooo :-)

Added autostart functionality and CLI to the digital twin application.

---

vnfs/dt-digitaltwin-emulator/containers/Dockerfile

Fix: Build fix because of broken python-statemachine locale

---

sdk-projects/tng-smpilot-ns1-k8s/Definitions/nsd/nsd_smpilot_ns1_emulator.yml
sdk-projects/tng-smpilot-ns1-k8s/Definitions/vnfd/vnfd_cc_emulator.yml
sdk-projects/tng-smpilot-ns1-k8s/Definitions/vnfd/vnfd_eae_emulator.yml
sdk-projects/tng-smpilot-ns1-k8s/TOSCA-Metadata/NAPD.yaml
sdk-projects/tng-smpilot-ns1-k8s/TOSCA-Metadata/TOSCA.meta
sdk-projects/tng-smpilot-ns1-k8s/etsi_manifest.mf
sdk-projects/tng-smpilot-ns1-k8s/project.yml

Signed-off-by: Felipe Vicens <felipe.vicens@atos.net>

Adding k8s template draft working descriptor

---

Jenkinsfile
README.md
pipeline/build/build.sh
pipeline/build/install-sdk.sh
pipeline/build/pack.sh
pipeline/publish/publish.sh
pipeline_local.sh

First steps towards Jenkins integration. #49

---

README.md
pipeline/build/install-sdk.sh
sdk-projects/pack.sh
sdk-projects/tng-smpilot-ns2-emulator/vnfd/vnfd_rtr_emulator.yml

Try to fix validator issue
Workaround. Closes #49

Feature 49

---

sdk-projects/pack.sh
sdk-projects/tng-smpilot-ns1-k8s/Definitions/vnfd/vnfd_cc_emulator.yml
sdk-projects/tng-smpilot-ns1-k8s/Definitions/vnfd/vnfd_eae_emulator.yml
sdk-projects/tng-smpilot-ns2-emulator/nsd/nsd_smpilot_ns2_emulator.yml
sdk-projects/tng-smpilot-ns2-emulator/vnfd/vnfd_rtr_emulator.yml

Try to be more compatible to the validator. But doesn't help much.

---

k8s/ns1.yaml
k8s/ns2.yaml
vnfs/dt-digitaltwin-docker/containers/Dockerfile.vimemu
vnfs/dt-digitaltwin-docker/containers/start.vimemu.sh
vnfs/dt-digitaltwin-docker/containers/stop.vimemu.sh
vnfs/mdc-machinedatacollector-docker/containers/Dockerfile.vimemu
vnfs/mdc-machinedatacollector-docker/containers/start.vimemu.sh

* First version of k8s descriptor for NS2
* Separate versions for DT and MDC for k8s
See #72

Started porting NS2 to k8s

---

vnfs/cc-cloudconnector-docker/containers/cdu_broker/start.sh
vnfs/cc-cloudconnector-docker/containers/cdu_processor/CC_VNF/CC_VNF.py
vnfs/cc-cloudconnector-docker/containers/cdu_processor/start.sh
vnfs/dt-digitaltwin-docker/containers/start.sh
vnfs/mdc-machinedatacollector-docker/containers/start.sh

:vimemu version is unchanged (stdout is written to file there)

changed k8s containers to log directly to stdout (much easier debugging)

---

vnfs/cc-cloudconnector-docker/containers/cdu_broker/Dockerfile
vnfs/cc-cloudconnector-docker/containers/cdu_processor/Dockerfile
vnfs/eae-edgeanalyticsengine-docker/containers/Dockerfile

curl, wget, dnsutils to debug container interconnection

Added debug packages to k8s containers

---

pipeline/publish/publish.sh
vnfs/build_docker_vnfs.sh
vnfs/cc-cloudconnector-docker/containers/cdu_database/Dockerfile.vimemu
vnfs/cc-cloudconnector-docker/containers/cdu_database/README.md
vnfs/cc-cloudconnector-docker/containers/cdu_database/prometheus.yml
vnfs/cc-cloudconnector-docker/containers/cdu_pushgateway/Dockerfile.vimemu
vnfs/cc-cloudconnector-docker/containers/cdu_pushgateway/README.md

Added initial Docker containers for CC Prometheus integration

---

k8s/ns1/cc-broker.yaml
k8s/ns1/eae.yaml

simple ClusterIP service + fixed DNS in microk8s --> connection between CC borker and subscriber works
still have to update CC processor scripts to use the correct service name

fixed service for CC broker

---

sdk-projects/tng-smpilot-ns1-emulator/vnfd/vnfd_cc_emulator.yml
sdk-projects/tng-smpilot-ns1-emulator/vnfd/vnfd_eae_emulator.yml
sdk-projects/tng-smpilot-ns2-emulator/vnfd/vnfd_dt_emulator.yml
sdk-projects/tng-smpilot-ns2-emulator/vnfd/vnfd_mdc_emulator.yml
sdk-projects/tng-smpilot-ns2-emulator/vnfd/vnfd_rtr_emulator.yml

Added port mapping and publishing ports. Only works with latest vim emu.

---

k8s/ns2/mdc.yaml

added k8s service for mdc

---

vnfs/cc-cloudconnector-docker/containers/cdu_processor/CC_VNF/CC_VNF.py
vnfs/cc-cloudconnector-docker/containers/cdu_processor/CC_VNF/prometheus.py
vnfs/cc-cloudconnector-docker/containers/cdu_processor/Dockerfile
vnfs/cc-cloudconnector-docker/containers/cdu_processor/Dockerfile.vimemu

Major step towards #92.
Needs some more testing bevor it is done.

Finally integrated Prometheus DB as local storage for metrics into CC.

---

k8s/metallb-conf.yml
k8s/ns1/cc.yml
k8s/ns1/eae.yaml
k8s/ns2/mdc.yaml
sdk-projects/tng-smpilot-ns1-k8s/Definitions/nsd/nsd_smpilot_ns1.yml
sdk-projects/tng-smpilot-ns1-k8s/Definitions/vnfd/vnfd_cc.yml
sdk-projects/tng-smpilot-ns1-k8s/Definitions/vnfd/vnfd_eae.yml
sdk-projects/tng-smpilot-ns2-k8s/nsd/nsd_smpilot_ns2.yml
sdk-projects/tng-smpilot-ns2-k8s/vnfd/vnfd_mdc.yml

According to @felipevicens 's example
Relates to #76

Updated VNFDs for deployment on K8s with SP

---

sdk-projects/pack-ns1-k8s.sh
sdk-projects/pack-ns2-k8s.sh

added scripts for packaging just ns1 or ns2 for k8s

---

README.md
vnfs/dt-digitaltwin-docker/containers/Dockerfile
vnfs/dt-digitaltwin-docker/containers/Dockerfile.vimemu

Added demo overview to readme

---

sdk-projects/tng-smpilot-ns1-emulator/vnfd/vnfd_eae_emulator.yml
vnfs/eae-edgeanalyticsengine-docker/containers/Dockerfile.vimemu
vnfs/eae-edgeanalyticsengine-docker/containers/dashboard.json
vnfs/eae-edgeanalyticsengine-docker/containers/dashboard_provider.yml
vnfs/eae-edgeanalyticsengine-docker/containers/datasource.yml
vnfs/eae-edgeanalyticsengine-docker/containers/start.vimemu.sh

Final fixes for EAE. EAE now works well in Emulator and is ready for

---

sdk-projects/tng-smpilot-ns1-k8s/Definitions/vnfd/vnfd_cc.yml
sdk-projects/tng-smpilot-ns1-k8s/Definitions/vnfd/vnfd_eae.yml
sdk-projects/tng-smpilot-ns2-k8s/vnfd/vnfd_mdc.yml
vnfs/build_docker_vnfs.sh

To ensure that Kubernetes always automatically pulls the latest image: https://kubernetes.io/docs/concepts/containers/images/#updating-images

Use :latest tag for k8s deployment

---

pipeline/publish/publish.sh

publish :lastest images

---

vnfs/cc-cloudconnector-docker/containers/cdu_processor/Dockerfile.vimemu
vnfs/dt-digitaltwin-docker/containers/IMMS_APP/IMMS_APP.py

Fix: Fixes issue that EM63 thread eats up 100 percent of CPU time.

---

vnfs/build_docker_vnfs.sh
vnfs/eae-edgeanalyticsengine-docker/containers/Dockerfile.vimemu

Fix: Container build

---

sdk-projects/netsoft_instantiate_stage1.sh
sdk-projects/netsoft_instantiate_stage2.sh

Fix: Directly connect services upon instantiation

---

pipeline/build/pack.sh

Testing CI

---

vnfs/dt-digitaltwin-docker/containers/Dockerfile
vnfs/dt-digitaltwin-docker/containers/Dockerfile.vimemu
vnfs/dt-digitaltwin-docker/containers/IMMS_APP/IMMS_APP.py
vnfs/dt-digitaltwin-docker/containers/IMMS_APP/OPC_UA_SERVER.py
vnfs/dt-digitaltwin-docker/containers/IMMS_APP/README.md
vnfs/dt-digitaltwin-docker/containers/requirements.txt

Adds OPC UA support for the IMMS as well as a corresponding example OPC UA server.

Add OPC UA Support for IMMS.

---

vnfs/eae-edgeanalyticsengine-docker/containers/start.sh

write Grafana logs to output; works better with k8s

---

sdk-projects/pack-ns2-ids-k8s.sh

just small helper script. similar to ns1 and ns2

added script for packing ns2 with ids

---

sdk-projects/tng-smpilot-ns2-k8s-eids/vnfd/lh.yml
sdk-projects/tng-smpilot-ns2-k8s-eids/vnfd/msf.yml

Signed-off-by: Felipe Vicens <felipe.vicens@atos.net>

Adding volumes to CNFs lh and msf

---

fsms/mdc-fsm/mdc/__main__.py
fsms/mdc-fsm/setup.py

Fix: Correct entry point for FSM

---

fsms/mdc-fsm/mdc/mdcfsm.py
sdk-projects/inst_params_ns2.yml

* Get hostname of quarantine NS1 from NSR
* Set env var of MDC to new quarantine host
* Return response to reconfigure
Not tested yet
See #257

First FSM reconfiguration code

---

sdk-projects/tng-smpilot-ns2-emulator/vnfd/vnfd_mdc_emulator.yml

Publish all relevant Samba ports in emulator deployment.

---

tools/smp-ccs/README.md
tools/smp-ccs/src/smpccs/client.py

Testing and documentation

---

fsms/build.sh
pipeline/publish/publish.sh
sdk-projects/tng-smpilot-ns2-k8s-eids/nsd/mdc-selk.yml
sdk-projects/tng-smpilot-ns2-k8s-eids/vnfd/msf.yml
ssms/README.md
ssms/build.sh
ssms/configure_event.yml
ssms/ns2-ssm/ns2/ns2.py

* Implemented SSM that handles reconfiguration and requests reconfiguration of MDC FSM
* Included SSM in NS2 descriptor
* Updated FSM and SSM names

Initial version of SSM for NS2

---

fsms/mdc-fsm/mdc/mdcfsm.py

needs capital letters according to Thomas

fix fsm response status

---

ssms/ns2-ssm/Dockerfile
ssms/ns2-ssm/setup.py

Reactivating grpc installation to check why build on jenkins fails

---

sdk-projects/tng-smpilot-ns2-k8s-eids/nsd/mdc-selk.yml

Added SSM type task and monitor to the NSD

---

sdk-projects/pack.sh
sdk-projects/tng-smpilot-ns2-k8s/vnfd/vnfd_mdc.yml

Fixed outdated descriptor

---

ssms/ns2-ssm/ns2/ns2.py
tools/smp-ccs/README.md

SMP-CC client activated and registers to remote server on init event

---

tools/smp-ccs/src/smpccs/server.py

Fix: Flush all prints to be able to use `docker logs -f` to monitor

---

ssms/ns2-ssm/ns2/ns2.py

Make SSM more verbose

---

vnfs/dt-digitaltwin-docker/containers/IMMS_APP/IMMS_APP.py
vnfs/dt-digitaltwin-docker/containers/IMMS_APP/samba_access.py

Still old functionality, but prepared to integrate new Samba access library.
Belongs to #257

Modularize IMMS, extend Samba access library

---

fsms/mdc-fsm/mdc/__main__.py
fsms/mdc-fsm/mdc/mdc.py

Renamed MDC FSM class and files to be compatible with tng-sm tool

---

ssms/ns2-ssm/ns2/ns2.py

Feature: Sent quarantine state form SSM to FSM

---

vnfs/dt-digitaltwin-docker/containers/IMMS_APP/IMMS_APP.py
vnfs/dt-digitaltwin-docker/containers/IMMS_APP/samba/samba_access.py
vnfs/dt-digitaltwin-docker/containers/requirements.txt
vnfs/dt-digitaltwin-docker/containers/start.sh

That auto reconnects to the MDC before each operation. Still needs testing with reconfiguration
Fixes #257

Use custom Samba access Python module for IMMS

---

ssms/ns2-ssm/ns2/ns2.py

Added more debugging output for further testing

---

ssms/ns2-ssm/ns2/ns2.py

SSM debugging

---

sdk-projects/inst_params_ns2.yml
vnfs/dt-digitaltwin-docker/containers/Dockerfile
vnfs/dt-digitaltwin-docker/containers/IMMS_APP/IMMS_APP.py
vnfs/dt-digitaltwin-docker/containers/IMMS_APP/samba/samba_access.py

* Configurable host- and username via env vars. Affects the IDS! See https://github.com/sonata-nfv/tng-industrial-pilot/wiki/IDS-deployment#trigger-an-alarm
* Automatic cleanup of created files

Improved IMMS

---

fsms/configure_event.yml
fsms/mdc-fsm/mdc/mdc.py
ssms/ns2-ssm/ns2/ns2.py

Updated SSM and FSM to allow configuration of quarantine state is both

---

policies/industrial-pilot-Security-Policy.json
sdk-projects/inst_params_ns2.yml

Minor changes during testing

---

tools/smp-ccs/Dockerfile
tools/smp-ccs/setup.py
tools/smp-ccs/src/smpccs/server.py

- use port 80 as default
- port configuration with ENVs
- allow CORS requests

Improving SMP-CC REST API

---

tools/smp-ccs/README.md

Updated documentation

---

vnfs/build_usecase3.sh
vnfs/usecase3/containers/proxyvpn/squid.conf
vnfs/usecase3/containers/socat/Dockerfile
vnfs/usecase3/containers/socat/start.sh
vnfs/usecase3/containers/ssh/start.sh

socat container

---

ssms/ns2-ssm/Dockerfile
vnfs/usecase3/containers/socat/Dockerfile

install iptables in container

---

k8s/ns3/ns3.yaml

fix NS3 k8s descriptor

---

k8s/ns3/ns3.yaml
sdk-projects/pack-ns3-k8s.sh
sdk-projects/tng-smpilot-ns3-k8s/Definitions/nsd/nsd_smpilot_ns3.yml
sdk-projects/tng-smpilot-ns3-k8s/Definitions/vnfd/vnfd_connector.yml
sdk-projects/tng-smpilot-ns3-k8s/project.yml

prepared tango descriptors for ns3

---

k8s/ns3/allowPrivilegedSecurityPolicy.yaml
k8s/ns3/ns3.yaml
sdk-projects/tng-smpilot-ns3-k8s/Definitions/nsd/nsd_smpilot_ns3.yml
sdk-projects/tng-smpilot-ns3-k8s/Definitions/vnfd/vnfd_connector.yml

For deployment on Tango SP
Related to #29

Updated descriptors of UC3

---

policies/industrial-pilot-Security-Policy.json
sdk-projects/pack.sh
sdk-projects/tng-smpilot-ns2-k8s-eids/vnfd/lhc.yml
sdk-projects/tng-smpilot-ns2-k8s-eids/vnfd/msf.yml

* Fix: Removed MANO env vars from VNFDs in NS2 that were leading to IDS not working (similar to issue #340 )
* Minor updates in other descriptors
Related to #330

Fixes: Removed MANO env vars from VNFDs
